Feature/advantages
yurilov/team-9-ice-cream pull request #3
Opened 2021-11-12 21:52 UTC by julia-gnatyshyn

2021-11-13 07:49 UTC, yurilov commented on src/partials/advantages.html
> +    <div class="advantages-container container">
по бему назва контейнера `advantages__container`, але не впевнений що нам взагалі треба такий клас, думаю тут можна буде обійтися синтаксисом sass `.advantages { & .container { }}, якщо треба буде переопридылити стилы контейнера для твого блоку

2021-11-13 07:51 UTC, yurilov commented on src/partials/advantages.html
> +        <ul class="advantages-list list">
тут перший клас по бему буде так: `advantages__list`

2021-11-13 07:54 UTC, yurilov commented on src/partials/advantages.html
> +    <div class="advantages-container container">
і тут для семантичності потрібно додати h2.visually-hidden `<h2 class="visually-hidden">Advantages</h2>`

2021-11-13 07:55 UTC, yurilov commented on src/partials/advantages.html
> +            <li class="advantages-list__item">
блок у нас advantages, а все решта його елементи, тому клас `advantages__item`

2021-11-13 07:58 UTC, yurilov commented on src/partials/advantages.html
> +                <span  class="advantages-list__item-number">721</span>
це h3 к класом `advantages__number` або `advantages__tittle` (теж саме для двох наступних)

2021-11-13 08:00 UTC, yurilov commented on src/partials/advantages.html
> +                <p class="advantages-list__item-info">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
клас по бему `advantages__info`, бо це все елементи одного блоку, які поза цим блоком не мають змісту (а так в тебе получається блок advantages-list і його елемент item-info)

2021-11-14 11:00 UTC, yurilov requested changes
додав коментарі по коду

2021-11-14 19:31 UTC, julia-gnatyshyn commented
виправила класи і додала css для моб версії. подивись будь ласка чому з шрини 417 і менше псевдоелементи залазять на наст елемент. ніяк не можу знайти в чому проблема

2021-11-14 19:42 UTC, yurilov requested changes

2021-11-14 19:42 UTC, yurilov commented on src/partials/advantages.html
> +                <h3  class="advantages__number number-first">721</>
По бему, модифікатор записуємо так advantages__number--first
Теж саме для двох наступних

2021-11-14 19:42 UTC, yurilov commented on src/sass/components/_advantages.scss
> +    font-family: $mainFont;
Ця властивість вже для body задається

2021-11-14 19:42 UTC, yurilov commented on src/sass/components/_advantages.scss
> +    background-size: cover;
Спільні властивості можеш задати для псевдоелемнту advantages__number, а ті що різні вже окремо для модифікаторів

2021-11-14 19:42 UTC, yurilov commented on src/sass/components/_advantages.scss
> +    background-image: url(../images/advantages-icon2.png);
Потрібно ще медіа правилом задати @2х картинки

2021-11-14 19:48 UTC, yurilov requested changes

2021-11-14 19:48 UTC, yurilov commented on src/sass/components/_advantages.scss
> +    bottom: 70px;
Тут ніби має бути top, бо ти ж відносно номера їх вверх піднімаєш на -70px

2021-11-14 20:22 UTC, yurilov commented on src/partials/advantages.html
> +                <h3  class="advantages__number number-first">721</>
закриваючий тег пропущено

2021-11-14 20:31 UTC, yurilov commented
> виправила класи і додала css для моб версії. подивись будь ласка чому з шрини 417 і менше псевдоелементи залазять на наст елемент. ніяк не можу знайти в чому проблема

задай 
```
&__item {
    padding-top: 66px;
    position: relative;
  }
```

а для before top: 0; так тоді не будуть залазити на інші елементи

2021-11-14 21:40 UTC, julia-gnatyshyn commented on src/partials/advantages.html
> +                <h3  class="advantages__number number-first">721</>
advantages__number number--first

2021-11-14 21:44 UTC, julia-gnatyshyn commented on src/sass/components/_advantages.scss
> +    background-size: cover;
в один клас не виходить записати

2021-11-15 06:27 UTC, yurilov reviewed
```
.advantages__number::before {
position: absolute;
    display: block;
    top: 0;
    content: '';
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
}
```
один спільний стиль для всіх псевдоелементів
і окремий на кожну картинку окрмо, це зменшить кількість коду
```
&.number--second::before {
    width: 50px;
    height: 50px;
    background-image: url(../images/advantages-icon2.png);
    @media (min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx) {
      background-image: url(../images/advantages-icon2@2x.png);
    }
  }

```

2021-11-15 06:28 UTC, yurilov approved these changes

2021-11-15 06:28 UTC, merged