модалка с минимальными стилями и JS
yurilov/team-9-ice-cream pull request #7
Opened 2021-11-13 14:28 UTC by EvgeniyKramarenko

2021-11-13 17:09 UTC, yurilov commented on src/index.html
> +    <script src="./js/modal.js"></script>
це звідси забери, а скріпт підлючи в індекс js
`import './js/modal.js';`

2021-11-13 17:10 UTC, yurilov commented on src/partials/modal.html
> +                <use href="./images/icons.svg#icon-close"></use>
тут забереш точку і все буде ок

2021-11-14 12:14 UTC, EvgeniyKramarenko commented on src/partials/modal.html
> +                <use href="./images/icons.svg#icon-close"></use>
+

2021-11-14 12:15 UTC, EvgeniyKramarenko commented on src/index.html
> +    <script src="./js/modal.js"></script>
підключив

2021-11-14 12:51 UTC, yurilov requested changes
1. потрібні зміни по назвах класів
2. ти вроді не додав іконки з модалки нашої веб студії в спрайт, але ти їх плануєш використовувати, бо в коді є їхні id, то додай їх (або якщо хочеш, я можу додати, цього разу не мав би поломані додати 😅, бо просто скопіюю зі спрайту веб студії)

2021-11-14 12:51 UTC, yurilov commented on src/partials/buy-modal.html
> +            <p class="buy__modal__title modal__title">Buy now</p>
підправ трохи назви класів всюди бо по бему buy__modal__title такі назви не допускаються
можу запропонувати так: buy-modal блок, buy-modal__title елемент цього блоку
все решта в тебе ок, лише назви класів по бему потрібно підправити

2021-11-14 14:24 UTC, EvgeniyKramarenko commented on src/partials/buy-modal.html
> +            <p class="buy__modal__title modal__title">Buy now</p>
классы поправил и подключил две кнопки

2021-11-14 14:36 UTC, yurilov approved these changes

2021-11-14 14:36 UTC, merged